version: '3.8'

services:
  mssql_server:
    image: dev_sqlserver:2019
    # restart: unless-stopped
    user: mssql
    env_file: .env
    environment:
      - PATH=${SQL_PATH}:${PATH}
    volumes:
      - ./mssql/data:/var/opt/mssql/data
      - ./mssql/log:/var/opt/mssql/log
      - ./mssql/backup:/var/opt/mssql/backup
      - ./mssql/secrets:/var/opt/mssql/secrets
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 10
    ports:
      - 1433:1433
    networks:
      - sql_network
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    depends_on:
      mssql_server:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P ${MSSQL_SA_PASSWORD} -d master -i docker-entrypoint-initdb.d/init.sql;
      echo "Data warehouse skeleton created!";
      '

networks:
  sql_network:
    external: true
